[package]
name = "pam-oauth2"
version = "0.1.0"
authors = ["Nick Cao <nickcao@nichi.co>"]
edition = "2018"

[lib]
crate_type = ["dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pam-sys = "0.5.6"
