[package]
name = "pam-oauth2"
version = "0.1.0"
authors = ["Nick Cao <nickcao@nichi.co>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
pam-sys = "0.5.6"
oauth2 = { version = "4.0.0-beta.1", default-features = false, features = [ "ureq" ] }
